### ISSUE TITLE
Sign-off workflow doesn't like hyphens in names

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/backend-meta#18]
(Pretty sure my diagnosis is right, eyeballing the regex that the script uses)

See e.g. https://github.com/matrix-org/complement/pull/622#issue-1609679169 for example

**Comment by hughns** [comment]
It looks like it wouldn't allow a `'` or diacritics more generally.

Perhaps replacing the `[\w ]+` with `[^<>]+` would suffice.

**Comment by Half-Shot** [comment]
Fixed in #20
